# Generated by Django 2.2.4 on 2019-12-24 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduateadmission',
            name='gre_score',
        ),
    ]
