# Generated by Django 2.2.4 on 2019-12-24 01:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_graduateadmission_gre_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduateadmission',
            name='lor_rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='graduateadmission',
            name='research',
            field=models.PositiveIntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
        migrations.AddField(
            model_name='graduateadmission',
            name='sop_rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='graduateadmission',
            name='toefl_score',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AddField(
            model_name='graduateadmission',
            name='university_rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='graduateadmission',
            name='gre_score',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(260), django.core.validators.MaxValueValidator(340)]),
        ),
    ]
