# Generated by Django 2.2.4 on 2019-12-24 02:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_auto_20191224_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduateadmission',
            name='cgpa',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
