# Generated by Django 2.2.4 on 2019-12-24 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_graduateadmission_cgpa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduateadmission',
            name='name',
        ),
    ]
