# Generated by Django 2.2.4 on 2019-12-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduateadmission',
            name='name',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
